### PR TITLE
Extend Base.gradient instead of defining a new one on 0.4

### PR DESCRIPTION
**Pull request by yuyichao**
Not sure if this is the best long term solution but at least it makes all tests pass and IMHO produce the least breakage for users.

### CODE REVIEW

**Comment by mlubin** [comment]
Gradient is on 0.3 also, no need to special case for 0.4.

**Comment by yuyichao** [comment]
I C. So it's the recently introduced handling of conflict export that breaks this, rather than the conflicting names themselves......

**Comment by mlubin** [comment]
Appears so

**Comment by yuyichao** [comment]
Updated

**Comment by mlubin** [comment]
I don't think this was the right solution. There's more than one method to compute the gradient of a function. I don't think the Calculus version should be any special and take over the ``gradient(::Function)`` method.

**Comment by johnmyleswhite** [comment]
I agree.

@mlubin: What do you think of trying to pull this package apart into separate packages for finite differentiation and symbolic differentiation? Now that ForwardDiff is out, I feel like I could take the work I did long ago on Calculus2 and try to adopt your API. We could then start to deprecate this package.

**Comment by mlubin** [comment]
Splitting into FiniteDiff and SymbolicDiff seems like a good idea. Both
could be hosted under JuliaDiff. Are the integration features in Calculus
useful?
@jrevels

**Comment by johnmyleswhite** [comment]
No, the integration functionality is far inferior to what's in Base.

**Comment by jrevels** [comment]
> What do you think of trying to pull this package apart into separate packages for finite differentiation and symbolic differentiation?

> Splitting into FiniteDiff and SymbolicDiff seems like a good idea.

I like this idea.

> Now that ForwardDiff is out, I feel like I could take the work I did long ago on Calculus2 and try to adopt your API.

That would be great. I stumbled upon Calculus2 a while ago and was hoping the effort would be revived soon! Let me know how I can help, and feel free to file issues in ForwardDiff.jl if anything needs to change API-wise there to make things work out.

**Pull request merged**
