### PR TITLE
Turn on precompilation

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Just FYI, @timholy, I'm working on splitting out the finite difference code and the symbolic differentiation code so that we can two new packages to replace this one. They'll share the same interface as ForwardDiff to make it easier to transition between the packages.

**Comment by timholy** [comment]
Good to know, and thanks for your efforts here!

**Comment by timholy** [comment]
Possible to tag a new release? I'm getting test failures due to the ambiguous-precompilation-order problem.

**Comment by johnmyleswhite** [comment]
I'll do a tag now

**Pull request merged**
